/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:da8cfd07-f70a-4248-a4bc-68487c20be83",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7jnyLouuH",
    "aws_user_pools_web_client_id": "2aa9gndeg5g5e6anl8v817gmlb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://w7xamhymr5exloemndnor4ix3i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
